In [1]:
import torch

In [12]:
a=torch.arange(10).reshape(5,2).unsqueeze(1)
b=torch.arange(10).reshape(5,2).unsqueeze(0)
a,b

(tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]],
 
         [[6, 7]],
 
         [[8, 9]]]),
 tensor([[[0, 1],
          [2, 3],
          [4, 5],
          [6, 7],
          [8, 9]]]))

In [24]:
(-0.5 * (a - b).pow(2).sum(-1) / 0.1).exp()

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
(a - b).pow(2).sum(-1).sqrt()

tensor([[ 0.0000,  2.8284,  5.6569,  8.4853, 11.3137],
        [ 2.8284,  0.0000,  2.8284,  5.6569,  8.4853],
        [ 5.6569,  2.8284,  0.0000,  2.8284,  5.6569],
        [ 8.4853,  5.6569,  2.8284,  0.0000,  2.8284],
        [11.3137,  8.4853,  5.6569,  2.8284,  0.0000]])

In [33]:
c=torch.arange(10).reshape(5,2).flatten(1)
c.shape,c

(torch.Size([10]), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [29]:
a.shape

torch.Size([5, 1, 2])